apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-apply
  labels:
    app: kubernetes-apply
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-apply
  template:
    metadata:
      labels:
        app: kubernetes-apply
    spec:
      containers:
      - name: kubernetes-apply
        image: ${artifact.image}:${artifact.tag}
        env:
          %{ for k,v in entrypoint.env }
          - name: ${k}
            value: "${v}"
          %{ endfor }
          # Ensure we set PORT for the URL service. This is only necessary
          # if we want the URL service to function.
          - name: PORT
            value: "8080"
