apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: gitops-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-example
  template:
    metadata:
      labels:
        app: gitops-example
    spec:
      containers:
      - name: gitops-example
        image: ${artifact.image}:${artifact.tag}
        env:
          %{ for k,v in entrypoint.env }
          - name: ${k}
            value: "${v}"
          %{ endfor }
          # Ensure we set PORT for the URL service. This is only necessary
          # if we want the URL service to function.
          - name: PORT
            value: "3000"
